name = "Marek Slany"
downloads-dir = "/home/morpheus/downloads"
watch-cmds = ["mpv ${XDG_CONFIG_HOME}/himalaya/hunter_killer.mp3"]

[69]
default = true
email = "marek.slany69@gmail.com"
mailboxes = { inbox = "INBOX", sent = "[Gmail]/Odeslan&AOE- po&AWE-ta", draft = "[Gmail]/Koncepty"}

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "marek.slany69@gmail.com"
imap-passwd-cmd = "pass show mail.google.com/app-marek.slany69@gmail.com"

smtp-host  = "smtp.gmail.com"
smtp-port = 465
smtp-login = "marek.slany69@gmail.com"
smtp-passwd-cmd = "pass show mail.google.com/app-marek.slany69@gmail.com"

[2003]
email = "marek.slany2003@gmail.com"
mailboxes = { inbox = "INBOX", sent = "[Gmail]/Odeslan&AOE- po&AWE-ta", draft = "[Gmail]/Koncepty"}

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "marek.slany2003@gmail.com"
imap-passwd-cmd = "pass show mail.google.com/app-marek.slany2003@gmail.com"

smtp-host  = "smtp.gmail.com"
smtp-port = 465
smtp-login = "marek.slany2003@gmail.com"
smtp-passwd-cmd = "pass show mail.google.com/app-marek.slany2003@gmail.com"
