#! /bin/sh

# start the background
wal -i /home/morpheus/.config/wallpaper/bg18.jpg
# source the colors.
# shellcheck source="/home/morpheus/.cache/wal/colors.sh"
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

pgrep -x sxhkd > /dev/null || sxhkd &

uwufetch | alacritty &
"$HOME"/.config/polybar/launch.sh &
pb on

# switch caps for escape
setxkbmap -option caps:swapescape &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zathura state=tiled
bspc rule -a android-studio state=floating

#Some stuff for java applications
wmname LG3D

#Start redshift
redshift &
