#!/usr/bin/bash

# The name which precedes the number of the background
bg_name="bg"
# The length of the numbering e.g. 01 would be 2, 001 would be 3 etc.
numbering_len=2

fehbg="$HOME/.fehbg"

# Where the wallpapers are stored
wallpaper="$HOME/.config/wallpaper/"

wallpaper_count=$(( $( find "$wallpaper" | wc -l ) - 1 ))

bg_num=$(( 10#$(sed -n "2p" "$fehbg" | grep -Po "(?<=$bg_name)\d\d(?=\.)") ))

# Adds zeroes to numbers with less digits then numbering_len
add_leading_zeros () {

	bg_num=$1
	len=${#bg_num}
	while [[ $len -lt $numbering_len ]]
	do
		bg_num="0$bg_num"
		len=${#bg_num}
	done

	echo "$bg_num"
}

if [[ $1 = "next" ]]
then
	if [[ $bg_num != "$wallpaper_count" ]]
	then
		bg_num=$(( bg_num + 1 ))
	else
		bg_num=1
	fi
	bg_num=$( add_leading_zeros $bg_num )
	bg=$( find "$wallpaper" | grep "$bg_name$bg_num" )
	wal -i -n "$bg"
	feh --bg-max "$bg"

elif [[ $1 = "previous" ]]
then
	if [[ $bg_num != 1 ]]
	then
		bg_num=$(( bg_num - 1 ))
	else
		bg_num=$wallpaper_count
	fi
	bg_num=$( add_leading_zeros "$bg_num" )
	bg=$( find "$wallpaper" | grep "$bg_name$bg_num" )
	wal -i -n "$bg"
	feh --bg-max "$bg"

elif [[ $1 = "status" ]]
then
	echo "Current wallpaper: $bg_num"
	wal --preview

else
	echo "Invalid argument, try:"
	echo "	next - changes to the next wallpaper"
	echo "	previous - changes to previous wallpaper"
	echo "	status - shows current background number"
fi
