#!/usr/bin/bash
# simple script to launch dmenu with colors from wal

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

dmenu_run -fn "-misc-hermit-bold-i-normal--17-120-100-*-m-0-iso10646-*" -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"
