#!/usr/bin/bash

CONFIG="/etc/systemd/logind.conf"

if [[ $1 = "toggle" ]]; then
{
	sudo sed -i '/HandleLidSwitch=ignore/{s/HandleLidSwitch=ignore/HandleLidSwitch=suspend/;p;d};s/HandleLidSwitch=suspend/HandleLidSwitch=ignore/' $CONFIG ; sudo killall -HUP systemd-logind
	sudo cat $CONFIG | rg "HandleLidSwitch="
}
elif [[ $1 = "on" ]]; then
{
	sudo sed -i 's/HandleLidSwitch=ignore/HandleLidSwitch=suspend/g' $CONFIG ; sudo killall -HUP systemd-logind
	sudo cat $CONFIG | rg "HandleLidSwitch="
}
elif [[ $1 = "off" ]]; then
{
	sudo sed -i 's/HandleLidSwitch=suspend/HandleLidSwitch=ignore/g' $CONFIG ; sudo killall -HUP systemd-logind
	sudo cat $CONFIG | rg "HandleLidSwitch="
}
elif [[ $1 = "info" ]]; then
{
	sudo cat $CONFIG | rg "HandleLidSwitch="
}
else
{
	echo "Invalid argument, try:"
	echo "	toggle - toggle sleep behaviour on lid close"
	echo "	on - turn sleep on"
	echo "	off - turn sleep off"
	echo "	info - print info abour current config"
}
fi
