#!/usr/bin/env sh

# Use xinput list and do a search for touchpads. Then get the first one and get its name.
device="ETPS/2 Elantech Touchpad"

# If it was activated disable it and if it wasn't disable it
if [ "$(xinput list-props "$device" | grep -P ".*Device Enabled.*\K.(?=$)" -o)" = "1" ];then 
{
    xinput disable "$device"
}
else
{
    xinput enable "$device"
}
fi
